version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v19.2.2
    command: start --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: "no"
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
  nakama:
    image: heroiclabs/nakama-clientsdk-test:latest
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
          exec /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257 --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100
    restart: "no"
    depends_on:
      - cockroachdb
    expose:
      - "7349"
      - "7350"
    ports:
      - "7349:7349"
      - "7350:7350"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5

  nakama-dotnet:
    image: heroiclabs/nakama-dotnet:latest
    depends_on:
      - nakama
    network_mode: "host"


